[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/L_Dunya.L_Dunya
GameDefaultMap=/Game/L_Dunya.L_Dunya
GlobalDefaultGameMode=/Script/KayipKrallik.KKGameMode
GameInstanceClass=/Script/KayipKrallik.KKGameInstance

[/Script/Engine.RendererSettings]
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.Bloom=True
r.AntiAliasingMethod=2

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Mobile
AppliedTargetedHardwareClass=Mobile
DefaultGraphicsPerformance=Scalable
AppliedDefaultGraphicsPerformance=Scalable

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
PackageName=com.mehmet.kayipkrallik
bSupportsVulkan=True
bBuildForES31=True
bPackageDataInsideApk=True

[/Script/Engine.CollisionProfile]
; Varsayilan profiller yeterli (Faz 0). Ozel kanal gerekirse Faz 1'de eklenir.
